services:
  tf:
    build:
      args:
        RUBY_VERSION: '3.0.4'
        TERRAFILE_VERSION: '0.7'
        TERRAFORM_COMPLIANCE_VERSION: '1.3.33'
        TERRAFORM_DOCS_VERSION: '0.16.0'
        TERRAGRUNT_VERSION: '0.38.12'
        TFENV_VERSION: '3.0.0'
        TFLINT_VERSION: '0.40.0'
        TFSEC_VERSION: '1.27.6'
      context: .
      labels:
        io.whalebrew.name: 'tf'
        io.whalebrew.required_version: '>0.3.0'
        io.whalebrew.config.environment: |
          [
            "TFLINT_PLUGIN_DIR=/opt/tflint/plugins",
            "TF_PLUGIN_CACHE_DIR=/opt/terraform-plugin-cache",
            "TF_VERBOSE",
          ]
        #io.whalebrew.config.keep_container_user: 'true'
        #io.whalebrew.config.missing_volumes: 'error' # Possible values are: 'error' | 'skip' | 'mount'
        io.whalebrew.config.networks: '["host"]'
        #io.whalebrew.config.ports: '["8100:8100"]'
        io.whalebrew.config.volumes: |
          [
            "~/.terraform.d/plugin-cache:/opt/terraform-plugin-cache:rw",
            "~/.tfenv/version:/opt/tfenv/version:rw",
            "~/.tfenv/versions:/opt/tfenv/versions:rw",
            "~/.tflint.d:/opt/tflint/plugins:rw",
          ]
        #io.whalebrew.config.volumes_from_args: '["-C", "--exec-path"]'
        #io.whalebrew.config.working_dir: '${PWD}'
    image: 'matefarkas/whalebrew-tf'
