services:
  tf:
    build:
      args:
        RUBY_VERSION: '3.0.4'
      context: .
      labels:
        io.whalebrew.name: 'tf'
        io.whalebrew.required_version: '>0.3.0'
        io.whalebrew.config.environment: '["PATH=/opt/tfenv/bin:/usr/local/bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "TF_VERBOSE"]'
        #io.whalebrew.config.keep_container_user: 'true'
        #io.whalebrew.config.missing_volumes: 'error' # Possible values are: 'error' | 'skip' | 'mount'
        #io.whalebrew.config.networks: '["host"]'
        #io.whalebrew.config.ports: '["8100:8100"]'
        io.whalebrew.config.volumes: '["~/.tfenv/version:/opt/tfenv/version:rw", "~/.tfenv/versions:/opt/tfenv/versions:rw"]'
        #io.whalebrew.config.volumes_from_args: '["-C", "--exec-path"]'
        #io.whalebrew.config.working_dir: '${PWD}'
    image: 'matefarkas/whalebrew-tf'
